# Generated by Django 4.2.9 on 2026-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_festivalconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='participant',
            name='accetta_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='accetta_statuto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='cap',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='citta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='codice_fiscale',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='data_di_nascita',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='indirizzo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='luogo_di_nascita',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='provincia',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='metodo_pagamento',
            field=models.CharField(choices=[('stripe', 'Stripe / Carta di Credito'), ('paypal', 'PayPal'), ('contanti', 'Contanti (Pagamento in loco)')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='pagato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('approved', 'Approvato'), ('rejected', 'Rifiutato'), ('checked_in', 'Partecipante arrivato')], default='approved', max_length=20),
        ),
    ]
