# Generated by Django 4.2.9 on 2026-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_remove_participant_payment_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='registration',
        ),
        migrations.AddField(
            model_name='participant',
            name='metodo_pagamento',
            field=models.CharField(choices=[('stripe', 'Stripe / Carta di Credito'), ('paypal', 'PayPal'), ('contanti', 'Contanti (Pagamento in loco)')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='pagato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='codice_fiscale',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa di pagamento'), ('approved', 'Approvato'), ('rejected', 'Rifiutato'), ('checked_in', 'Partecipante arrivato')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
