# Generated by Django 4.2.9 on 2025-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_registration_alter_participant_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='type',
            field=models.CharField(choices=[('drinks', 'Solo bere'), ('dinner', 'Cena')], default='drinks', max_length=20),
        ),
    ]
