# Generated by Django 4.2.9 on 2026-06-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_participant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='payment_proof',
        ),
    ]
