# Generated by Django 4.2.9 on 2026-06-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_remove_registration_payment_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='type',
        ),
    ]
