# Generated by Django 4.2.9 on 2026-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_remove_participant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price_centesimi', models.PositiveIntegerField(default=1050)),
            ],
            options={
                'verbose_name': 'Configurazione Festival',
                'verbose_name_plural': 'Configurazioni Festival',
            },
        ),
    ]
