# Generated by Django 4.2.9 on 2026-07-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_remove_participant_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='qr_code',
        ),
    ]
